nutz:
  application:
    name: wk-device-handler

platform:
  #第三方平台接入配置项
  aep: #AEP平台配置项
    url:
    appId:
    appKey:
    appSecret:

database:
  enable: false #是否启用数据库功能

rocketmq:
  # 集群环境多个nameserver用;分割
  nameserver-address: 127.0.0.1:9876
  # 生产者组
  producer-group: wk_local_producer
  consumer-thread-max: 0
  consumer-thread-min: 0

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 2000
  max_redir: 10
  database: 0
  maxTotal: 100
  password:
  pool:
    maxTotal: 100
    maxIdle: 50
    minIdle: 10
  # cluster 集群模式
  mode: normal
  # cluster 集群模式
  #nodes:
redisson:
  # 集群/分片/主从等配置见 https://github.com/nutzam/nutzmore/tree/master/nutz-integration-redisson
  mode: single
  single:
    address: redis://127.0.0.1:6379
    #password: pass123
    database: 0

nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    namespace: dev
    naming:
      service-name: budwk.device_handler
      meta-data: "{'version':'budwk.device_handler.8.0.0'}"
  config:
    server-addr: 127.0.0.1:8848
    namespace: dev #千万别写 public 因为查询条件是命名空间ID,而nacos默认的public命名空间ID是空白!!!
    data-id: wk-device_handler
    data-type: yaml
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?namespace=dev
  protocol:
    name: dubbo
    threads: 200
    #随机端口
    port: 0
    #默认关闭QOS服务
  application:
    qos:
      enable: false

device:
  storage:
    # 原始报文存储时间(单位天,默认30天  仅对mongodb有效)
    raw-save-ttl: 30
    # 解析后数据存储时间(单位天,默认0=永久存储  仅对mongodb有效,tdengine 是建库语句设置)
    data-save-ttl: 0
    # 解析后数据存储方式(mongodb/tdengine)
    data-save-type: mongodb

mongodb:
  url: mongodb://127.0.0.1:27017/budwk_v8_device

log:
  level: debug
  color: true